version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: uglify-js
    versions:
    - 3.12.5
    - 3.13.0
    - 3.13.2
  - dependency-name: clipboard
    versions:
    - 2.0.7
  - dependency-name: jasmine
    versions:
    - 3.6.4
